MK_CFG_DIR = /home/y/share/make_cfg
include $(MK_CFG_DIR)/make.defs

EXETARGET = atomic_symlink
CSRC = atomic_symlink.c
CXXSRC = 

WARN +=
OPPFLAGS +=
LDFLAGS =
LDLIBS = 

include $(MK_CFG_DIR)/make.rules
